# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kdoctools': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kcompletion': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
