# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kdoctools': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kcompletion': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
