#!/bin/sh
#
# substitute <source> <dest>

AWK=/usr/bin/awk
SED=/usr/bin/sed
ET_DIR=/var/home/coolo/prod/kdeutils/kfloppy/e2fs/lib/et
SS_DIR=/var/home/coolo/prod/kdeutils/kfloppy/e2fs/lib/ss
E2FSPROGS_MONTH=October
E2FSPROGS_YEAR=1996
E2FSPROGS_VERSION=1.06
SIZEOF_LONG_LONG=8
SIZEOF_LONG=4
SIZEOF_INT=4
SIZEOF_SHORT=2

MV=/bin/mv
RM=/bin/rm
CP=/bin/cp


#
# This is the actual gots of substitute_sh.  It is in a separate file to 
# protect it from autoconf substitutions
#

$SED 	-e "s%@AWK@%$AWK%g" \
	-e "s%@SED@%$SED%g" \
	-e "s%@ET_DIR@%$ET_DIR%g" \
	-e "s%@SS_DIR@%$SS_DIR%g" \
	-e "s%@E2FSPROGS_MONTH@%$E2FSPROGS_MONTH%g" \
	-e "s%@E2FSPROGS_YEAR@%$E2FSPROGS_YEAR%g" \
	-e "s%@E2FSPROGS_VERSION@%$E2FSPROGS_VERSION%g" \
	-e "s%@SIZEOF_LONG_LONG@%$SIZEOF_LONG_LONG%g" \
	-e "s%@SIZEOF_LONG@%$SIZEOF_LONG%g" \
	-e "s%@SIZEOF_INT@%$SIZEOF_INT%g" \
	-e "s%@SIZEOF_SHORT@%$SIZEOF_SHORT%g" \
	$1 > $2.tmp

if [ -f $2 ]; then
	if cmp $2 $2.tmp > /dev/null 2>&1 ; then
		$RM $2.tmp
	else
		echo "substitute_sh: Replacing $2"
		$MV $2.tmp $2
	fi
else
	echo "substitute_sh: Creating $2"
	$MV $2.tmp $2
fi
